library(RDHonest)
library(tidyverse)

ggplot(data = lee08) + geom_histogram(aes(y=..density..,x = margin),alpha = 0.4) + theme_minimal()  + xlim(0,99)
ggsave("images/lee_hist.png")
ggplot(data = lee08) + geom_histogram(aes(y=..density..,x = margin),alpha = 0.4) + geom_density(aes(y=..density..,x = margin)) + theme_minimal()  + xlim(0,99)
ggsave("images/lee_density.png")
ggplot(data = lee08) +  geom_density(aes(y=..density.. ,x = margin), bw = 1)  + theme_minimal() + xlim(0,99)
ggsave("images/lee_density_bw1.png")
ggplot(data = lee08) +  geom_density(aes(y=..density.. ,x = margin), bw = 0.1)  + theme_minimal() + xlim(0,99)
ggsave("images/lee_density_bw2.png")
